# Site settings
title:          Salafi Manhaj
description:    "Salafi manhaj"
baseurl:        "/"
url:            "https://salafimanhaj.github.io"

lang: ["en", "ar"]

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Admin
  email:        xx@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks

paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         alsalafiyyah

defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: default
  -
    scope:
      path: "ar"
    values:
      lang: "ar"
