title:          Salafi Manhaj
description:    "Salafi manhaj"
baseurl:        "/"
url:            "https://salafimanhaj.github.io"
google_analytics: UAâ€”XXXXXXXX-X
author:
  name:         Instagram@Alsalafiyyah
  email:        alsalafiyyah@icloud.com
markdown:       kramdown
include:
  - _pages
sass:
  sass_dir:     _sass
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
permalink: /:title/
paginate:       10
exclude: [ Gemfile ]
disqus:         alsalafiyyah
